# Guild-specific Config file

guild:
    id: 839457899360157706
    invite:
    name: Myself

bot:
    prefix:

ext:
    adv_replies:
        enabled: true
    danked_memer:
        enabled: true
    messagehook:
        enabled: true
    reactomatic:
        enabled: true
    welcomer:
        enabled: true
        welcome_channel: 8394578993601577098
    anti_spam:
        enabled: true
    counting:
        enabled: true
    mod_utils:
        enabled: true
    nerd_utils:
        enabled: true
    simple_games:
        enabled: true
